//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace YaHZ.modeling_test
{
	/// <summary>
	/// DomainRelationship ExampleModelHasExampleElements
	/// Description for YaHZ.modeling_test.ExampleModelHasExampleElements
	/// </summary>
	[DslDesign::DisplayNameResource("YaHZ.modeling_test.ExampleModelHasExampleElements.DisplayName", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("YaHZ.modeling_test.ExampleModelHasExampleElements.Description", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::YaHZ.modeling_test.modeling_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("3e463951-2f37-4d72-9806-f1108f021246")]
	public partial class ExampleModelHasExampleElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleModelHasExampleElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x3e463951, 0x2f37, 0x4d72, 0x98, 0x06, 0xf1, 0x10, 0x8f, 0x02, 0x12, 0x46);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleModelHasExampleElements link in the same Partition as the given ExampleModel
		/// </summary>
		/// <param name="source">ExampleModel to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleModelHasExampleElements(ExampleModel source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleModelHasExampleElements.ExampleModelDomainRoleId, source), new DslModeling::RoleAssignment(ExampleModelHasExampleElements.ExampleElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasExampleElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasExampleElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasExampleElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasExampleElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ExampleModel domain role code
		
		/// <summary>
		/// ExampleModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleModelDomainRoleId = new global::System.Guid(0x4d4039b6, 0xacc9, 0x40a7, 0x8b, 0xb7, 0xcd, 0x96, 0x06, 0x76, 0x59, 0x7b);
		
		/// <summary>
		/// DomainRole ExampleModel
		/// Description for YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleModel
		/// </summary>
		[DslDesign::DisplayNameResource("YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleModel.DisplayName", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleModel.Description", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "ExampleElements", PropertyDisplayNameKey="YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("4d4039b6-acc9-40a7-8bb7-cd960676597b")]
		public virtual ExampleModel ExampleModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleModel of a ExampleElement
		/// <summary>
		/// Gets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ExampleModel GetExampleModel(ExampleElement element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ExampleElementDomainRoleId) as ExampleModel;
		}
		
		/// <summary>
		/// Sets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetExampleModel(ExampleElement element, ExampleModel newExampleModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ExampleElementDomainRoleId, newExampleModel);
		}
		#endregion
		#region ExampleElement domain role code
		
		/// <summary>
		/// ExampleElement domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleElementDomainRoleId = new global::System.Guid(0x8520ed70, 0x7d09, 0x4e96, 0xad, 0xb2, 0xe7, 0xb9, 0xa4, 0x50, 0xa0, 0x75);
		
		/// <summary>
		/// DomainRole ExampleElement
		/// Description for YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleElement
		/// </summary>
		[DslDesign::DisplayNameResource("YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleElement.DisplayName", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleElement.Description", typeof(global::YaHZ.modeling_test.modeling_testDomainModel), "YaHZ.modeling_test.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ExampleModel", PropertyDisplayNameKey="YaHZ.modeling_test.ExampleModelHasExampleElements/ExampleElement.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("8520ed70-7d09-4e96-adb2-e7b9a450a075")]
		public virtual ExampleElement ExampleElement
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleElements of a ExampleModel
		/// <summary>
		/// Gets a list of ExampleElements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetExampleElements(ExampleModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleModel link accessor
		/// <summary>
		/// Get the list of ExampleModelHasExampleElements links to a ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::YaHZ.modeling_test.ExampleModelHasExampleElements> GetLinksToExampleElements ( global::YaHZ.modeling_test.ExampleModel exampleModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::YaHZ.modeling_test.ExampleModelHasExampleElements>(exampleModelInstance, global::YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleElement link accessor
		/// <summary>
		/// Get the ExampleModelHasExampleElements link to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::YaHZ.modeling_test.ExampleModelHasExampleElements GetLinkToExampleModel (global::YaHZ.modeling_test.ExampleElement exampleElementInstance)
		{
			global::System.Collections.Generic.IList<global::YaHZ.modeling_test.ExampleModelHasExampleElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::YaHZ.modeling_test.ExampleModelHasExampleElements>(exampleElementInstance, global::YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ExampleElement not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ExampleModelHasExampleElements instance accessors
		
		/// <summary>
		/// Get any ExampleModelHasExampleElements links between a given ExampleModel and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::YaHZ.modeling_test.ExampleModelHasExampleElements> GetLinks( global::YaHZ.modeling_test.ExampleModel source, global::YaHZ.modeling_test.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::YaHZ.modeling_test.ExampleModelHasExampleElements> outLinks = new global::System.Collections.Generic.List<global::YaHZ.modeling_test.ExampleModelHasExampleElements>();
			global::System.Collections.Generic.IList<global::YaHZ.modeling_test.ExampleModelHasExampleElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::YaHZ.modeling_test.ExampleModelHasExampleElements>(source, global::YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleModelDomainRoleId);
			foreach ( global::YaHZ.modeling_test.ExampleModelHasExampleElements link in links )
			{
				if ( target.Equals(link.ExampleElement) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleModelHasExampleElements link between a given ExampleModeland a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::YaHZ.modeling_test.ExampleModelHasExampleElements GetLink( global::YaHZ.modeling_test.ExampleModel source, global::YaHZ.modeling_test.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::YaHZ.modeling_test.ExampleModelHasExampleElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::YaHZ.modeling_test.ExampleModelHasExampleElements>(source, global::YaHZ.modeling_test.ExampleModelHasExampleElements.ExampleModelDomainRoleId);
			foreach ( global::YaHZ.modeling_test.ExampleModelHasExampleElements link in links )
			{
				if ( target.Equals(link.ExampleElement) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
