[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "YaHZ.modeling_test.Constants.#modeling_testDiagramMenu")]
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaHZ.modeling_test
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "modelingtest";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"modeling_test";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"YaHZ";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID modeling_testDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(modeling_testCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID modeling_testExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(modeling_testCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID Viewmodeling_testExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(modeling_testCommandSetId), 0x0001);
	
		// Package identifier
		public const string modeling_testPackageId = "f5d1e2b1-3a3d-4a7e-862f-40bb45000db9";
		
		// Editor factory identifier
		public const string modeling_testEditorFactoryId = "c2c4da82-9d8a-4b5a-a5ed-072e77af6fef";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string modeling_testModelExplorerToolWindowId = "8fcaa8d5-ddc1-4a56-b4ef-4657563a7e18";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace YaHZ.modeling_test
{
	using System.Diagnostics.CodeAnalysis;
	
	internal static partial class Constants
	{
		// Menu identifier
		public const string modeling_testCommandSetId = "bda66d5e-e632-4239-8cdc-e1228159008b";
	}
}